=== CredentialEngine/CredentialRegistry/fixtures/schemas/navy/cost_manifest_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"$ref": "#/definitions/ceterms:CostManifest",
	"definitions": {
		"@context": {
			"type": "string",
			"enum": [
				"http://credreg.net/ctdl/schema/context/json"
			]
		},
		"@id": {
			"type": "string"
		},
		"@id_multi": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/@id"
			}
		},
		"@id_absolute": {
			"type": "string",
			"format": "uri"
		},
		"@id_absolute_multi": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/@id_absolute"
			}
		},
		"meta:string": {
			"type": "string"
		},
		"meta:string_multi": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/meta:string"
			}
		},
		"meta:langstring": {
			"type": "string"
		},
		"meta:langstring_multi": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/meta:langstring"
			}
		},
		"meta:literal_object": {
			"type": "object",
			"properties": {
				"@id": {
					"$ref": "#/definitions/@id"
				},
				"@value": {
					"$ref": "#/definitions/meta:string"
				},
				"@language": {
					"$ref": "#/definitions/meta:string"
				}
			}
		},
		"meta:literal": {
			"anyOf": [
				{
					"$ref": "#/definitions/meta:string"
				},
				{
					"$ref": "#/definitions/meta:literal_object"
				}
			]
		},
		"meta:literal_multi": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/meta:literal"
			}
		},
		"ceterms:CostManifest": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:CostManifest"
					]
				},
				"@context": {
					"$ref": "#/definitions/@context"
				},
				"@id": {
					"$ref": "#/definitions/@id"
				},
				"ceterms:costDetails": {
					"$ref": "#/definitions/ceterms:costDetails"
				},
				"ceterms:costManifestOf": {
					"$ref": "#/definitions/ceterms:costManifestOf"
				},
				"ceterms:ctid": {
					"$ref": "#/definitions/ceterms:ctid"
				},
				"ceterms:description": {
					"$ref": "#/definitions/ceterms:description"
				},
				"ceterms:endDate": {
					"$ref": "#/definitions/ceterms:endDate"
				},
				"ceterms:estimatedCost": {
					"$ref": "#/definitions/ceterms:estimatedCost"
				},
				"ceterms:name": {
					"$ref": "#/definitions/ceterms:name"
				},
				"ceterms:startDate": {
					"$ref": "#/definitions/ceterms:startDate"
				}
			},
			"required": [
				"@type",
				"@id",
				"ceterms:costDetails",
				"ceterms:costManifestOf",
				"ceterms:ctid",
				"ceterms:description"
			],
			"additionalProperties": false
		},
		"ceterms:CostProfile": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:CostProfile"
					]
				},
				"ceterms:audienceType": {
					"$ref": "#/definitions/ceterms:audienceType"
				},
				"ceterms:condition": {
					"$ref": "#/definitions/ceterms:condition"
				},
				"ceterms:costDetails": {
					"$ref": "#/definitions/ceterms:costDetails"
				},
				"ceterms:currency": {
					"$ref": "#/definitions/ceterms:currency"
				},
				"ceterms:description": {
					"$ref": "#/definitions/ceterms:description"
				},
				"ceterms:directCostType": {
					"$ref": "#/definitions/ceterms:directCostType"
				},
				"ceterms:endDate": {
					"$ref": "#/definitions/ceterms:endDate"
				},
				"ceterms:jurisdiction": {
					"$ref": "#/definitions/ceterms:jurisdiction"
				},
				"ceterms:name": {
					"$ref": "#/definitions/ceterms:name"
				},
				"ceterms:paymentPattern": {
					"$ref": "#/definitions/ceterms:paymentPattern"
				},
				"ceterms:price": {
					"$ref": "#/definitions/ceterms:price"
				},
				"ceterms:region": {
					"$ref": "#/definitions/ceterms:region"
				},
				"ceterms:residencyType": {
					"$ref": "#/definitions/ceterms:residencyType"
				},
				"ceterms:startDate": {
					"$ref": "#/definitions/ceterms:startDate"
				}
			},
			"required": [
				"@type",
				"ceterms:costDetails",
				"ceterms:description"
			],
			"additionalProperties": false
		},
		"ceterms:CredentialAlignmentObject": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:CredentialAlignmentObject"
					]
				},
				"ceterms:alignmentDate": {
					"$ref": "#/definitions/ceterms:alignmentDate"
				},
				"ceterms:alignmentType": {
					"$ref": "#/definitions/ceterms:alignmentType"
				},
				"ceterms:codedNotation": {
					"$ref": "#/definitions/ceterms:codedNotation"
				},
				"ceterms:framework": {
					"$ref": "#/definitions/ceterms:framework"
				},
				"ceterms:frameworkName": {
					"$ref": "#/definitions/ceterms:frameworkName"
				},
				"ceterms:targetNode": {
					"$ref": "#/definitions/ceterms:targetNode"
				},
				"ceterms:targetNodeDescription": {
					"$ref": "#/definitions/ceterms:targetNodeDescription"
				},
				"ceterms:targetNodeName": {
					"$ref": "#/definitions/ceterms:targetNodeName"
				},
				"ceterms:weight": {
					"$ref": "#/definitions/ceterms:weight"
				}
			},
			"required": [
				"@type",
				"ceterms:targetNodeName"
			],
			"additionalProperties": false
		},
		"ceterms:JurisdictionProfile": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:JurisdictionProfile"
					]
				},
				"ceterms:assertedBy": {
					"$ref": "#/definitions/ceterms:assertedBy"
				},
				"ceterms:description": {
					"$ref": "#/definitions/ceterms:description"
				},
				"ceterms:globalJurisdiction": {
					"$ref": "#/definitions/ceterms:globalJurisdiction"
				},
				"ceterms:jurisdictionException": {
					"$ref": "#/definitions/ceterms:jurisdictionException"
				},
				"ceterms:mainJurisdiction": {
					"$ref": "#/definitions/ceterms:mainJurisdiction"
				}
			},
			"required": [
				"@type"
			],
			"additionalProperties": false
		},
		"ceterms:Place": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:Place"
					]
				},
				"ceterms:addressCountry": {
					"$ref": "#/definitions/ceterms:addressCountry"
				},
				"ceterms:addressLocality": {
					"$ref": "#/definitions/ceterms:addressLocality"
				},
				"ceterms:addressRegion": {
					"$ref": "#/definitions/ceterms:addressRegion"
				},
				"ceterms:description": {
					"$ref": "#/definitions/ceterms:description"
				},
				"ceterms:geoURI": {
					"$ref": "#/definitions/ceterms:geoURI"
				},
				"ceterms:latitude": {
					"$ref": "#/definitions/ceterms:latitude"
				},
				"ceterms:longitude": {
					"$ref": "#/definitions/ceterms:longitude"
				},
				"ceterms:name": {
					"$ref": "#/definitions/ceterms:name"
				},
				"ceterms:postalCode": {
					"$ref": "#/definitions/ceterms:postalCode"
				},
				"ceterms:postOfficeBoxNumber": {
					"$ref": "#/definitions/ceterms:postOfficeBoxNumber"
				},
				"ceterms:streetAddress": {
					"$ref": "#/definitions/ceterms:streetAddress"
				},
				"ceterms:targetContactPoint": {
					"$ref": "#/definitions/ceterms:targetContactPoint"
				}
			},
			"required": [
				"@type"
			],
			"additionalProperties": false
		},
		"ceterms:ContactPoint": {
			"type": "object",
			"properties": {
				"@type": {
					"enum": [
						"ceterms:ContactPoint"
					]
				},
				"ceterms:contactOption": {
					"$ref": "#/definitions/ceterms:contactOption"
				},
				"ceterms:contactType": {
					"$ref": "#/definitions/ceterms:contactType"
				},
				"ceterms:email": {
					"$ref": "#/definitions/ceterms:email"
				},
				"ceterms:faxNumber": {
					"$ref": "#/definitions/ceterms:faxNumber"
				},
				"ceterms:name": {
					"$ref": "#/definitions/ceterms:name"
				},
				"ceterms:socialMedia": {
					"$ref": "#/definitions/ceterms:socialMedia"
				},
				"ceterms:telephone": {
					"$ref": "#/definitions/ceterms:telephone"
				}
			},
			"required": [
				"@type"
			],
			"additionalProperties": false
		},
		"ceterms:costDetails": {
			"$ref": "#/definitions/@id_absolute"
		},
		"ceterms:costManifestOf": {
			"$ref": "#/definitions/pointer:constraint:ReferenceOrganization"
		},
		"ceterms:ctid": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:description": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:endDate": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:estimatedCost": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:CostProfile"
			}
		},
		"ceterms:name": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:startDate": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:audienceType": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:CredentialAlignmentObject"
			}
		},
		"ceterms:condition": {
			"$ref": "#/definitions/meta:langstring_multi"
		},
		"ceterms:currency": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:directCostType": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:CredentialAlignmentObject"
			}
		},
		"ceterms:jurisdiction": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:JurisdictionProfile"
			}
		},
		"ceterms:paymentPattern": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:price": {
			"type": "number"
		},
		"ceterms:region": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:Place"
			}
		},
		"ceterms:residencyType": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:CredentialAlignmentObject"
			}
		},
		"ceterms:alignmentDate": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:alignmentType": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:codedNotation": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:framework": {
			"$ref": "#/definitions/@id_absolute"
		},
		"ceterms:frameworkName": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:targetNode": {
			"$ref": "#/definitions/@id_absolute"
		},
		"ceterms:targetNodeDescription": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:targetNodeName": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:weight": {
			"type": "number"
		},
		"ceterms:assertedBy": {
			"$ref": "#/definitions/pointer:constraint:ReferenceOrganization"
		},
		"ceterms:globalJurisdiction": {
			"type": "boolean"
		},
		"ceterms:jurisdictionException": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:Place"
			}
		},
		"ceterms:mainJurisdiction": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:Place"
			}
		},
		"ceterms:addressCountry": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:addressLocality": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:addressRegion": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:geoURI": {
			"$ref": "#/definitions/@id_absolute"
		},
		"ceterms:latitude": {
			"type": "number"
		},
		"ceterms:longitude": {
			"type": "number"
		},
		"ceterms:postalCode": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:postOfficeBoxNumber": {
			"$ref": "#/definitions/meta:string"
		},
		"ceterms:streetAddress": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:targetContactPoint": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/ceterms:ContactPoint"
			}
		},
		"ceterms:contactOption": {
			"$ref": "#/definitions/meta:langstring_multi"
		},
		"ceterms:contactType": {
			"$ref": "#/definitions/meta:langstring"
		},
		"ceterms:email": {
			"$ref": "#/definitions/meta:string_multi"
		},
		"ceterms:faxNumber": {
			"$ref": "#/definitions/meta:string_multi"
		},
		"ceterms:socialMedia": {
			"$ref": "#/definitions/@id_absolute_multi"
		},
		"ceterms:telephone": {
			"$ref": "#/definitions/meta:string_multi"
		},
		"pointer:constraint:ReferenceOrganization": {
			"anyOf": [
				{
					"type": "array",
					"properties": {
						"@id": {
							"$ref": "#/definitions/@id_absolute"
						}
					},
					"required": [
						"@id"
					],
					"additionalProperties": false
				},
				{
					"type": "array",
					"properties": {
						"@type": {
							"enum": [
								"ceterms:CredentialOrganization",
								"ceterms:QACredentialOrganization"
							]
						},
						"ceterms:name": {
							"$ref": "#/definitions/ceterms:name"
						},
						"ceterms:description": {
							"$ref": "#/definitions/ceterms:description"
						},
						"ceterms:subjectWebpage": {
							"$ref": "#/definitions/ceterms:subjectWebpage"
						},
						"ceterms:socialMedia": {
							"$ref": "#/definitions/ceterms:socialMedia"
						}
					},
					"required": [
						"@type"
					],
					"additionalProperties": false
				}
			]
		}
	}
}

=== CredentialEngine/CredentialRegistry/db/seeds/ce_registry/cost_manifest_schema.json
[{"@context":"http://credreg.net/ctdl/schema/context/json","@id":"http://lr-staging.learningtapestry.com/resources/ce-7697332f-97d1-47a3-80b0-158f0140761c","@type":"ceterms:CostManifest","ceterms:costDetails":"https://financialaid.sf.edu/tuition-fees","ceterms:costManifestOf":[{"@id":"http://lr-staging.learningtapestry.com/resources/ce-a799a6db-1544-493b-9d73-978ea112beec"}],"ceterms:ctid":"ce-7697332f-97d1-47a3-80b0-158f0140761c","ceterms:description":"As one of the lowest priced private universities in the state, USF represents a tremendous value and is a wonderful investment in your future.  Most students, even those who may not have financial need, receive scholarships at the University of Saint Francis. In addition, funds from state and federal grants, private scholarships, loans and work-study may be available for you.","ceterms:estimatedCost":[{"@type":"ceterms:CostProfile","ceterms:audienceType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:FullTime","ceterms:targetNodeName":"Full-Time"}],"ceterms:costDetails":"https://financialaid.sf.edu/paying-for-college/net-price-calculator/","ceterms:description":"The University of Saint Francis is committed to making education as affordable as possible. The only application USF requires to determine financial aid eligibility is the FAFSA (Free Application for Federal Student Aid). The FAFSA is available every year after October 1 and should be completed prior to April 15 prior to the start of an academic year to ensure students receive the maximum amount of aid for which they are eligible. Prior to being able to apply for financial aid, we want to afford students the opportunity to determine an estimate of their financial aid eligibility prior to the FAFSA being made available. Please complete the appropriate Net Price Calculator to see how affordable USF can be.","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:Tuition","ceterms:targetNodeName":"Tuition"}],"ceterms:name":" Net Price Calculator","ceterms:paymentPattern":"Tuition for 12-18 credit hours","ceterms:price":28390.0}],"ceterms:name":"Tuition and Fees (Undergraduate)"},{"@context":"http://credreg.net/ctdl/schema/context/json","@id":"http://lr-staging.learningtapestry.com/resources/ce-1188ddc3-84b0-42ed-9db0-62b80a06016a","@type":"ceterms:CostManifest","ceterms:costDetails":"https://www.elon.edu/e/admissions/undergraduate/financial-aid/index.html","ceterms:costManifestOf":[{"@id":"http://lr-staging.learningtapestry.com/resources/ce-33b14188-1871-4d75-b065-45cf7edeece4"}],"ceterms:ctid":"ce-1188ddc3-84b0-42ed-9db0-62b80a06016a","ceterms:description":"Elon University is committed to providing an exceptional education at a reasonable cost.","ceterms:estimatedCost":[{"@type":"ceterms:CostProfile","ceterms:audienceType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:CurrentStudent","ceterms:targetNodeName":"Current Student"}],"ceterms:costDetails":"https://www.elon.edu/e/admissions/undergraduate/financial-aid/index.html","ceterms:currency":"US Dollar","ceterms:description":"For federal financial aid purposes, indirect costs including books, transportation, and miscellaneous expenses (set at $3,500) are added to tuition, fees, room, and board to determine Elon Universityâ€™s official total cost of attendance, which is $49,642 for 2017-2018.\n\n","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:AggregateCost","ceterms:targetNodeName":"Aggregate Cost"}],"ceterms:name":"Cost","ceterms:paymentPattern":"For 2017-2018","ceterms:price":49642.0}],"ceterms:name":"Elon University Tuition and Fees"},{"@context":"http://credreg.net/ctdl/schema/context/json","@id":"http://lr-staging.learningtapestry.com/resources/ce-f7066346-3e85-4d2c-bf1c-6919ab816800","@type":"ceterms:CostManifest","ceterms:costDetails":"http://www.energymanagementassociation.org/training/empprocessseminar.aspx","ceterms:costManifestOf":[{"@id":"http://lr-staging.learningtapestry.com/resources/ce-77f9fd94-9219-4346-bbb8-326f0d84e5e5"}],"ceterms:ctid":"ce-f7066346-3e85-4d2c-bf1c-6919ab816800","ceterms:description":"EMP certification is available to industry professionals who are responsible for managing and continually improving energy performance in commercial buildings. The scope of the EMP program is aligned with the Energy Management Professional consensus qualifications guidelines established by the U.S. Department of Energy.\n\nEMP certificants:\n\nPlan effective energy management\n\nManage energy information\n\nImplement energy management programs\n\nManage budgets and finances\n\nImplement energy efficient projects\n\nManage energy communications","ceterms:estimatedCost":[{"@type":"ceterms:CostProfile","ceterms:audienceType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:FullTime","ceterms:targetNodeName":"Full-Time"},{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:PublicEmployee","ceterms:targetNodeName":"Public Employee"}],"ceterms:costDetails":"http://www.energymanagementassociation.org/training/empprocessseminar.aspx","ceterms:currency":"US Dollar","ceterms:description":"Individuals employed by an EMA member company, or by a company that has submitted a completed application EMP Application \u0026 Exam Fee $500. All other individuals, $750.","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:Application","ceterms:targetNodeName":"Application"}],"ceterms:name":" EMA Employee","ceterms:price":500.0},{"@type":"ceterms:CostProfile","ceterms:audienceType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:FullTime","ceterms:targetNodeName":"Full-Time"},{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Audience","ceterms:targetNode":"audience:PublicEmployee","ceterms:targetNodeName":"Public Employee"}],"ceterms:costDetails":"http://www.energymanagementassociation.org/training/empprocessseminar.aspx","ceterms:currency":"US Dollar","ceterms:description":"Application costs for Non-EMA Employees","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:Application","ceterms:targetNodeName":"Application"}],"ceterms:name":" Non-EMA Employees","ceterms:price":750.0}],"ceterms:name":"Certification Fees"},{"@context":"http://credreg.net/ctdl/schema/context/json","@id":"http://lr-staging.learningtapestry.com/resources/ce-4fd52c37-f0d0-4499-b3e7-8c37a865fc3d","@type":"ceterms:CostManifest","ceterms:costDetails":"http://www.tstc.edu/admissions/tuition?_ga=2.67757458.206721200.1501095680-1754683349.1501095680","ceterms:costManifestOf":[{"@id":"http://lr-staging.learningtapestry.com/resources/ce-3cee9a46-97a7-41f2-955b-0220c4cead5a"}],"ceterms:ctid":"ce-4fd52c37-f0d0-4499-b3e7-8c37a865fc3d","ceterms:description":"The cost of attending Texas State Technical College (TSTC) varies depending on a variety of factors, such as residency status, whether or you live on campus, the program of study and any other services that you may need. You may be eligible for financial assistance which can help provide the financial support for tuition, housing, books and other educational items.","ceterms:estimatedCost":[{"@type":"ceterms:CostProfile","ceterms:costDetails":"http://www.tstc.edu/admissions/tuition","ceterms:currency":"US Dollar","ceterms:description":"The cost of attending Texas State Technical College (TSTC) varies depending on a variety of factors, such as residency status, whether or you live on campus, the program of study and any other services that you may need. You may be eligible for financial assistance which can help provide the financial support for tuition, housing, books and other educational items.\n\n","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:Tuition","ceterms:targetNodeName":"Tuition"}],"ceterms:name":"In-State Tuition ","ceterms:paymentPattern":"Tier 1 (Biomedical Equipment Technology, Computer Networking \u0026 Security, Culinary Arts, Dental Hygiene, Diesel Equipment Technology, Electrical Power \u0026 Controls Technology, Instrumentation Technology, Lineworker, Registered Nursing, Welding Technology): per credit hour\n\n","ceterms:price":188.0,"ceterms:residencyType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Residency","ceterms:targetNode":"residency:InState","ceterms:targetNodeName":"In-State"}]},{"@type":"ceterms:CostProfile","ceterms:costDetails":"http://www.tstc.edu/admissions/tuition","ceterms:currency":"US Dollar","ceterms:description":"The cost of attending Texas State Technical College (TSTC) varies depending on a variety of factors, such as residency status, whether or you live on campus, the program of study and any other services that you may need. You may be eligible for financial assistance which can help provide the financial support for tuition, housing, books and other educational items.\n\n","ceterms:directCostType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"CostType","ceterms:targetNode":"costType:Tuition","ceterms:targetNodeName":"Tuition"}],"ceterms:name":"In-State Tuition ","ceterms:paymentPattern":"Tier 2 (All technical classes not in Tier 1, All General Academic Courses): per credit hour","ceterms:price":166.0,"ceterms:residencyType":[{"@type":"ceterms:CredentialAlignmentObject","ceterms:framework":"Residency","ceterms:targetNode":"residency:InState","ceterms:targetNodeName":"In-State"}]},{"@type":"ceterms:CostProfile","ceterms:costDetails":"http://www.tstc.ed
